feat: add option to short relationships last in OperationDefinition
dimaMachina/graphql-eslint pull request #2385
Opened 2024-06-14 07:14 UTC by deathemperor

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.

Fixes https://github.com/dimaMachina/graphql-eslint/issues/2235

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
      expected)
- [x] This change requires a documentation update

## Screenshots/Sandbox (if appropriate/relevant):

N/A

## How Has This Been Tested?

I've been running this on our development code base

**Test Environment**:

- OS: MacOS 15
- "@graphql-eslint/eslint-plugin": "^3.20.1",
- NodeJS: 21.5.0

## Checklist:

- [x] I have followed the
      [CONTRIBUTING](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md) doc and the
      style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests and linter rules pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-18 07:37 UTC, deathemperor commented
@dimaMachina would you please review? thanks.

2024-11-14 09:56 UTC, dimaMachina requested changes
please rebase and add new `groups` option, similar as in [PR](https://github.com/dimaMachina/graphql-eslint/pull/2293)

2024-11-16 03:15 UTC, dimaMachina approved these changes

2024-11-16 03:22 UTC, merged

2024-11-18 02:24 UTC, deathemperor commented
thanks for the code rework @dimaMachina